/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicStarsRouteImport } from './routes/api/public/stars'
import { Route as ApiPublicConstellationsRouteImport } from './routes/api/public/constellations'
import { Route as ApiPublicStarsLatestRouteImport } from './routes/api/public/stars.latest'
import { Route as ApiPublicConstellationsPendingRouteImport } from './routes/api/public/constellations.pending'
import { Route as ApiPublicConstellationsCreateRouteImport } from './routes/api/public/constellations.create'
import { Route as ApiPublicConstellationsIdRouteImport } from './routes/api/public/constellations.$id'
import { Route as ApiPublicConstellationsIdUploadSynthRouteImport } from './routes/api/public/constellations.$id.upload-synth'
import { Route as ApiPublicConstellationsIdSynthAudioRouteImport } from './routes/api/public/constellations.$id.synth-audio'
import { Route as ApiPublicConstellationsIdMarkSynthesizingRouteImport } from './routes/api/public/constellations.$id.mark-synthesizing'
import { Route as ApiPublicConstellationsIdMarkReadyRouteImport } from './routes/api/public/constellations.$id.mark-ready'
import { Route as ApiPublicConstellationsIdMarkFailedRouteImport } from './routes/api/public/constellations.$id.mark-failed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStarsRoute = ApiPublicStarsRouteImport.update({
  id: '/api/public/stars',
  path: '/api/public/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConstellationsRoute = ApiPublicConstellationsRouteImport.update({
  id: '/api/public/constellations',
  path: '/api/public/constellations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStarsLatestRoute = ApiPublicStarsLatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => ApiPublicStarsRoute,
} as any)
const ApiPublicConstellationsPendingRoute =
  ApiPublicConstellationsPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => ApiPublicConstellationsRoute,
  } as any)
const ApiPublicConstellationsCreateRoute =
  ApiPublicConstellationsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => ApiPublicConstellationsRoute,
  } as any)
const ApiPublicConstellationsIdRoute =
  ApiPublicConstellationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicConstellationsRoute,
  } as any)
const ApiPublicConstellationsIdUploadSynthRoute =
  ApiPublicConstellationsIdUploadSynthRouteImport.update({
    id: '/upload-synth',
    path: '/upload-synth',
    getParentRoute: () => ApiPublicConstellationsIdRoute,
  } as any)
const ApiPublicConstellationsIdSynthAudioRoute =
  ApiPublicConstellationsIdSynthAudioRouteImport.update({
    id: '/synth-audio',
    path: '/synth-audio',
    getParentRoute: () => ApiPublicConstellationsIdRoute,
  } as any)
const ApiPublicConstellationsIdMarkSynthesizingRoute =
  ApiPublicConstellationsIdMarkSynthesizingRouteImport.update({
    id: '/mark-synthesizing',
    path: '/mark-synthesizing',
    getParentRoute: () => ApiPublicConstellationsIdRoute,
  } as any)
const ApiPublicConstellationsIdMarkReadyRoute =
  ApiPublicConstellationsIdMarkReadyRouteImport.update({
    id: '/mark-ready',
    path: '/mark-ready',
    getParentRoute: () => ApiPublicConstellationsIdRoute,
  } as any)
const ApiPublicConstellationsIdMarkFailedRoute =
  ApiPublicConstellationsIdMarkFailedRouteImport.update({
    id: '/mark-failed',
    path: '/mark-failed',
    getParentRoute: () => ApiPublicConstellationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/constellations': typeof ApiPublicConstellationsRouteWithChildren
  '/api/public/stars': typeof ApiPublicStarsRouteWithChildren
  '/api/public/constellations/$id': typeof ApiPublicConstellationsIdRouteWithChildren
  '/api/public/constellations/create': typeof ApiPublicConstellationsCreateRoute
  '/api/public/constellations/pending': typeof ApiPublicConstellationsPendingRoute
  '/api/public/stars/latest': typeof ApiPublicStarsLatestRoute
  '/api/public/constellations/$id/mark-failed': typeof ApiPublicConstellationsIdMarkFailedRoute
  '/api/public/constellations/$id/mark-ready': typeof ApiPublicConstellationsIdMarkReadyRoute
  '/api/public/constellations/$id/mark-synthesizing': typeof ApiPublicConstellationsIdMarkSynthesizingRoute
  '/api/public/constellations/$id/synth-audio': typeof ApiPublicConstellationsIdSynthAudioRoute
  '/api/public/constellations/$id/upload-synth': typeof ApiPublicConstellationsIdUploadSynthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/constellations': typeof ApiPublicConstellationsRouteWithChildren
  '/api/public/stars': typeof ApiPublicStarsRouteWithChildren
  '/api/public/constellations/$id': typeof ApiPublicConstellationsIdRouteWithChildren
  '/api/public/constellations/create': typeof ApiPublicConstellationsCreateRoute
  '/api/public/constellations/pending': typeof ApiPublicConstellationsPendingRoute
  '/api/public/stars/latest': typeof ApiPublicStarsLatestRoute
  '/api/public/constellations/$id/mark-failed': typeof ApiPublicConstellationsIdMarkFailedRoute
  '/api/public/constellations/$id/mark-ready': typeof ApiPublicConstellationsIdMarkReadyRoute
  '/api/public/constellations/$id/mark-synthesizing': typeof ApiPublicConstellationsIdMarkSynthesizingRoute
  '/api/public/constellations/$id/synth-audio': typeof ApiPublicConstellationsIdSynthAudioRoute
  '/api/public/constellations/$id/upload-synth': typeof ApiPublicConstellationsIdUploadSynthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/constellations': typeof ApiPublicConstellationsRouteWithChildren
  '/api/public/stars': typeof ApiPublicStarsRouteWithChildren
  '/api/public/constellations/$id': typeof ApiPublicConstellationsIdRouteWithChildren
  '/api/public/constellations/create': typeof ApiPublicConstellationsCreateRoute
  '/api/public/constellations/pending': typeof ApiPublicConstellationsPendingRoute
  '/api/public/stars/latest': typeof ApiPublicStarsLatestRoute
  '/api/public/constellations/$id/mark-failed': typeof ApiPublicConstellationsIdMarkFailedRoute
  '/api/public/constellations/$id/mark-ready': typeof ApiPublicConstellationsIdMarkReadyRoute
  '/api/public/constellations/$id/mark-synthesizing': typeof ApiPublicConstellationsIdMarkSynthesizingRoute
  '/api/public/constellations/$id/synth-audio': typeof ApiPublicConstellationsIdSynthAudioRoute
  '/api/public/constellations/$id/upload-synth': typeof ApiPublicConstellationsIdUploadSynthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/constellations'
    | '/api/public/stars'
    | '/api/public/constellations/$id'
    | '/api/public/constellations/create'
    | '/api/public/constellations/pending'
    | '/api/public/stars/latest'
    | '/api/public/constellations/$id/mark-failed'
    | '/api/public/constellations/$id/mark-ready'
    | '/api/public/constellations/$id/mark-synthesizing'
    | '/api/public/constellations/$id/synth-audio'
    | '/api/public/constellations/$id/upload-synth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/constellations'
    | '/api/public/stars'
    | '/api/public/constellations/$id'
    | '/api/public/constellations/create'
    | '/api/public/constellations/pending'
    | '/api/public/stars/latest'
    | '/api/public/constellations/$id/mark-failed'
    | '/api/public/constellations/$id/mark-ready'
    | '/api/public/constellations/$id/mark-synthesizing'
    | '/api/public/constellations/$id/synth-audio'
    | '/api/public/constellations/$id/upload-synth'
  id:
    | '__root__'
    | '/'
    | '/api/public/constellations'
    | '/api/public/stars'
    | '/api/public/constellations/$id'
    | '/api/public/constellations/create'
    | '/api/public/constellations/pending'
    | '/api/public/stars/latest'
    | '/api/public/constellations/$id/mark-failed'
    | '/api/public/constellations/$id/mark-ready'
    | '/api/public/constellations/$id/mark-synthesizing'
    | '/api/public/constellations/$id/synth-audio'
    | '/api/public/constellations/$id/upload-synth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicConstellationsRoute: typeof ApiPublicConstellationsRouteWithChildren
  ApiPublicStarsRoute: typeof ApiPublicStarsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stars': {
      id: '/api/public/stars'
      path: '/api/public/stars'
      fullPath: '/api/public/stars'
      preLoaderRoute: typeof ApiPublicStarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/constellations': {
      id: '/api/public/constellations'
      path: '/api/public/constellations'
      fullPath: '/api/public/constellations'
      preLoaderRoute: typeof ApiPublicConstellationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stars/latest': {
      id: '/api/public/stars/latest'
      path: '/latest'
      fullPath: '/api/public/stars/latest'
      preLoaderRoute: typeof ApiPublicStarsLatestRouteImport
      parentRoute: typeof ApiPublicStarsRoute
    }
    '/api/public/constellations/pending': {
      id: '/api/public/constellations/pending'
      path: '/pending'
      fullPath: '/api/public/constellations/pending'
      preLoaderRoute: typeof ApiPublicConstellationsPendingRouteImport
      parentRoute: typeof ApiPublicConstellationsRoute
    }
    '/api/public/constellations/create': {
      id: '/api/public/constellations/create'
      path: '/create'
      fullPath: '/api/public/constellations/create'
      preLoaderRoute: typeof ApiPublicConstellationsCreateRouteImport
      parentRoute: typeof ApiPublicConstellationsRoute
    }
    '/api/public/constellations/$id': {
      id: '/api/public/constellations/$id'
      path: '/$id'
      fullPath: '/api/public/constellations/$id'
      preLoaderRoute: typeof ApiPublicConstellationsIdRouteImport
      parentRoute: typeof ApiPublicConstellationsRoute
    }
    '/api/public/constellations/$id/upload-synth': {
      id: '/api/public/constellations/$id/upload-synth'
      path: '/upload-synth'
      fullPath: '/api/public/constellations/$id/upload-synth'
      preLoaderRoute: typeof ApiPublicConstellationsIdUploadSynthRouteImport
      parentRoute: typeof ApiPublicConstellationsIdRoute
    }
    '/api/public/constellations/$id/synth-audio': {
      id: '/api/public/constellations/$id/synth-audio'
      path: '/synth-audio'
      fullPath: '/api/public/constellations/$id/synth-audio'
      preLoaderRoute: typeof ApiPublicConstellationsIdSynthAudioRouteImport
      parentRoute: typeof ApiPublicConstellationsIdRoute
    }
    '/api/public/constellations/$id/mark-synthesizing': {
      id: '/api/public/constellations/$id/mark-synthesizing'
      path: '/mark-synthesizing'
      fullPath: '/api/public/constellations/$id/mark-synthesizing'
      preLoaderRoute: typeof ApiPublicConstellationsIdMarkSynthesizingRouteImport
      parentRoute: typeof ApiPublicConstellationsIdRoute
    }
    '/api/public/constellations/$id/mark-ready': {
      id: '/api/public/constellations/$id/mark-ready'
      path: '/mark-ready'
      fullPath: '/api/public/constellations/$id/mark-ready'
      preLoaderRoute: typeof ApiPublicConstellationsIdMarkReadyRouteImport
      parentRoute: typeof ApiPublicConstellationsIdRoute
    }
    '/api/public/constellations/$id/mark-failed': {
      id: '/api/public/constellations/$id/mark-failed'
      path: '/mark-failed'
      fullPath: '/api/public/constellations/$id/mark-failed'
      preLoaderRoute: typeof ApiPublicConstellationsIdMarkFailedRouteImport
      parentRoute: typeof ApiPublicConstellationsIdRoute
    }
  }
}

interface ApiPublicConstellationsIdRouteChildren {
  ApiPublicConstellationsIdMarkFailedRoute: typeof ApiPublicConstellationsIdMarkFailedRoute
  ApiPublicConstellationsIdMarkReadyRoute: typeof ApiPublicConstellationsIdMarkReadyRoute
  ApiPublicConstellationsIdMarkSynthesizingRoute: typeof ApiPublicConstellationsIdMarkSynthesizingRoute
  ApiPublicConstellationsIdSynthAudioRoute: typeof ApiPublicConstellationsIdSynthAudioRoute
  ApiPublicConstellationsIdUploadSynthRoute: typeof ApiPublicConstellationsIdUploadSynthRoute
}

const ApiPublicConstellationsIdRouteChildren: ApiPublicConstellationsIdRouteChildren =
  {
    ApiPublicConstellationsIdMarkFailedRoute:
      ApiPublicConstellationsIdMarkFailedRoute,
    ApiPublicConstellationsIdMarkReadyRoute:
      ApiPublicConstellationsIdMarkReadyRoute,
    ApiPublicConstellationsIdMarkSynthesizingRoute:
      ApiPublicConstellationsIdMarkSynthesizingRoute,
    ApiPublicConstellationsIdSynthAudioRoute:
      ApiPublicConstellationsIdSynthAudioRoute,
    ApiPublicConstellationsIdUploadSynthRoute:
      ApiPublicConstellationsIdUploadSynthRoute,
  }

const ApiPublicConstellationsIdRouteWithChildren =
  ApiPublicConstellationsIdRoute._addFileChildren(
    ApiPublicConstellationsIdRouteChildren,
  )

interface ApiPublicConstellationsRouteChildren {
  ApiPublicConstellationsIdRoute: typeof ApiPublicConstellationsIdRouteWithChildren
  ApiPublicConstellationsCreateRoute: typeof ApiPublicConstellationsCreateRoute
  ApiPublicConstellationsPendingRoute: typeof ApiPublicConstellationsPendingRoute
}

const ApiPublicConstellationsRouteChildren: ApiPublicConstellationsRouteChildren =
  {
    ApiPublicConstellationsIdRoute: ApiPublicConstellationsIdRouteWithChildren,
    ApiPublicConstellationsCreateRoute: ApiPublicConstellationsCreateRoute,
    ApiPublicConstellationsPendingRoute: ApiPublicConstellationsPendingRoute,
  }

const ApiPublicConstellationsRouteWithChildren =
  ApiPublicConstellationsRoute._addFileChildren(
    ApiPublicConstellationsRouteChildren,
  )

interface ApiPublicStarsRouteChildren {
  ApiPublicStarsLatestRoute: typeof ApiPublicStarsLatestRoute
}

const ApiPublicStarsRouteChildren: ApiPublicStarsRouteChildren = {
  ApiPublicStarsLatestRoute: ApiPublicStarsLatestRoute,
}

const ApiPublicStarsRouteWithChildren = ApiPublicStarsRoute._addFileChildren(
  ApiPublicStarsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicConstellationsRoute: ApiPublicConstellationsRouteWithChildren,
  ApiPublicStarsRoute: ApiPublicStarsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
